### ISSUE TITLE
Create/Set Method for generateID is too restrictive; panics on reasonable use case

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-data-go#7]
When I attempt to create/set an item using the IdentifiableMemoryPersistence and I don't do one of the following the code will panic (without any means to recover):
- If my data does not include a field with the name "Id"
- If my data does not have the appropriate data type (ostensibly)

In debugging the GetProperty() function, it never got into the if matchField() function to do anything and always returned nil. My object type is below:

```go
type Owner struct {
	ID    string `json:"Id"`
	Asset uint64 `json:"asset,string"`
	Job   uint64 `json:"job,string"`
	Site  uint64 `json:"site,string"`
}
```

Personally I'd rather it just not attempt to generate an ID (at all), but at the very least I'd rather it NOT panic on failure (i.e. fail open).

Panic log (edited for privacy):
```
=== RUN   TestMemoryPersistence
[---:TRACE:2021-07-16T20:21:14Z] Cleared items
=== RUN   TestMemoryPersistence/Test_CRUD
[---:TRACE:2021-07-16T20:21:14Z] Nothing to return as random item
--- FAIL: TestMemoryPersistence (0.00s)
    --- FAIL: TestMemoryPersistence/Test_CRUD (0.00s)
panic: Id field doesn't exist [recovered]
	panic: Id field doesn't exist

goroutine 20 [running]:
testing.tRunner.func1.2(0x7c5340, 0x983630)
	C:/Program Files/Go/src/testing/testing.go:1143 +0x345
testing.tRunner.func1(0xc000104c00)
	C:/Program Files/Go/src/testing/testing.go:1146 +0x4b6
panic(0x7c5340, 0x983630)
	C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
github.com/pip-services3-go/pip-services3-data-go/persistence.GenerateObjectId(0xc000115da8)
	C:/xxx/go/pkg/mod/github.com/pip-services3-go/pip-services3-data-go@v1.1.4/persistence/Utilities.go:194 +0x166
github.com/pip-services3-go/pip-services3-data-go/persistence.(*IdentifiableMemoryPersistence).Create(0xc00015a800, 0x0, 0x0, 0x833c80, 0xc000159a40, 0x0, 0x0, 0xc0001d9710, 0xc050a4e7b5)
	C:/xxx/go/pkg/mod/github.com/pip-services3-go/pip-services3-data-go@v1.1.4/persistence/IdentifiableMemoryPersistence.go:187 +0xaf
---
removed
---	
testing.tRunner(0xc000104c00, 0xc000245270)
	C:/Program Files/Go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1238 +0x2b3
FAIL	xxx/test/persistence	1.625s
```

**Comment by antonio-alexander** [comment]
Was doing some research into the bug and the above comment is half-true. The overall issue is that the underlying code can't properly parse the id field out of the given data type for OwnerGrouping (not owner):
```go
type Owner struct {
	ID    string `json:"id"`
	Asset uint64 `json:"asset,string"`
	Job   uint64 `json:"job,string"`
	Site  uint64 `json:"site,string"`
}

type OwnerGrouping struct {
	Owner
	Version  int32 `json:"version"`
	Modified int64 `json:"Modified,string"`
	Deleted  bool  `json:"Deleted"`
}
```

The code fails even IF I comment out the generateID field, so I expect just as it can't find the ID field, it can't produce it to write it to the table (for postgres). I think you can (1) fix the GetProperty() function's ability to traverse an unknown data type (if you don't care about efficiency you can marshal into bytes and unmarshal into map[string]interface{}) or (2) remove all existing code and require that the interface provided implement either/both a get/set id function to use instead of attempting to parse the unknown data type (that's a cleaner/Go way).

**Comment by antonio-alexander** [comment]
This code snippet seems to resolve the problem. I think there are probably some other use cases that will cause this code to fail (but I'm not sure what they are), this specifically fixes my problem (along with not having a field name of "Id"):
```go

// Gets value of object property specified by its name.
// Parameters:
//   - obj interface{}
//   an object to read property from.
//   - name string
//   a name of the property to get.
// Returns interface{}
// the property value or null if property doesn't exist or introspection failed.
func GetProperty(obj interface{}, name string) interface{} {
	if obj == nil || name == "" {
		return nil
	}

	obj = getValue(obj)
	val := reflect.ValueOf(obj)

	if val.Kind() == reflect.Map {
		name = strings.ToLower(name)
		for _, v := range val.MapKeys() {
			key := convert.StringConverter.ToString(v.Interface())
			key = strings.ToLower(key)
			if name == key {
				return val.MapIndex(v).Interface()
			}
		}
		return nil
	}

	defer func() {
		// Do nothing and return nil
		recover()
	}()

	fieldType := toFieldType(obj)
        //replaced existing code with recursive function
	if fieldType.Kind() == reflect.Struct {
		return getPropertyRecursive(fieldType, obj, name)
	}

	return nil
}

func getPropertyRecursive(fieldType reflect.Type, obj interface{}, name string) interface{} {
	for index := 0; index < fieldType.NumField(); index++ {
		field := fieldType.Field(index)
		val := reflect.ValueOf(obj)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch field.Type.Kind() {
		default:
			if matchField(field, name) {
				return val.Field(index).Interface()
			}
		case reflect.Struct:
			return getPropertyRecursive(field.Type, val.Field(index).Interface(), name)
		}
	}

	return nil
}
```

**Comment by antonio-alexander** [comment]
This code snippet is slightly updated so that it doesn't just work when a specific order is provided. In testing I found that if the Id wasn't in the first struct, it would return early and still panic.
```go

// Gets value of object property specified by its name.
// Parameters:
//   - obj interface{}
//   an object to read property from.
//   - name string
//   a name of the property to get.
// Returns interface{}
// the property value or null if property doesn't exist or introspection failed.
func GetProperty(obj interface{}, name string) interface{} {
	if obj == nil || name == "" {
		return nil
	}

	obj = getValue(obj)
	val := reflect.ValueOf(obj)

	if val.Kind() == reflect.Map {
		name = strings.ToLower(name)
		for _, v := range val.MapKeys() {
			key := convert.StringConverter.ToString(v.Interface())
			key = strings.ToLower(key)
			if name == key {
				return val.MapIndex(v).Interface()
			}
		}
		return nil
	}

	defer func() {
		// Do nothing and return nil
		recover()
	}()

	fieldType := toFieldType(obj)
	if fieldType.Kind() == reflect.Struct {
		return getPropertyRecursive(fieldType, obj, name)
	}

	return nil
}

func getPropertyRecursive(fieldType reflect.Type, obj interface{}, name string) interface{} {
	for index := 0; index < fieldType.NumField(); index++ {
		field := fieldType.Field(index)
		val := reflect.ValueOf(obj)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch field.Type.Kind() {
		default:
			if matchField(field, name) {
				return val.Field(index).Interface()
			}
		case reflect.Struct:
			if item := getPropertyRecursive(field.Type, val.Field(index).Interface(), name); item != nil {
				return item
			}
		}
	}

	return nil
}
```

**Comment by levichevdmitry** [comment]
Hi @antonio-alexander !
Thank you for your research in the localization of the problem and help in solving it.
I fixed the problem based on your code.
For nested structures, I've added some extra tests, so everything should work.
Please update to the latest version (v1.1.6) and test in your code.
